name: check-edge

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  edge-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: "2.8.3"
      - working-directory: services/polaris-functions
        run: deno check main.ts
      - working-directory: services/polaris-functions
        run: deno test --allow-net --allow-read --allow-env .
      - working-directory: services/polaris-functions
        run: deno lint .
